include:
  - board: nice_nano_v2
    shield: totem_central dongle_display
    snippet: studio-rpc-usb-uart
    artifact-name: totem_central
  - board: seeeduino_xiao_ble
    shield: totem_left
    snippet: studio-rpc-usb-uart
  - board: seeeduino_xiao_ble
    shield: totem_right
  - board: nice_nano_v2
    shield: settings_reset
  - board: seeeduino_xiao_ble
    shield: settings_reset
# there is no settingsreset (needed) for the XIAO
